
organizationbase:
  replicaCount: 2
  autoscaling:
    maxPods: 15
  iamRole: k8s-jenkins
  appName: kekseapp
  appVersion: "1.0"
  container:
    livenessEndpoint: /actuator/health
    readynessEndpoint: /actuator/health
    limits:
      cpu: 2000m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingress:
    dnsName: kekseapp
